### ISSUE TITLE
buildlog-lasercutter-marlin

### ISSUE THREAD

**Issue by timschmidt** [mkeyno/CNC-Laser-Shield#1]
Hi!

I'm the original developer of the buildlog-lasercutter-marlin code in the LMN repo.  Your work looks awesome!  I'm pretty excited to see what you've done so far, porting it to the due.

Development of that code has moved here: https://github.com/timschmidt/buildlog-lasercutter-marlin and I'd be happy to collaborate with you!

--tim

**Comment by mkeyno** [comment]
hi @timschmidt , thanks for noticing ,actually I'm just novice and with help of cool  guys like [ TurnkeyTyranny](https://github.com/TurnkeyTyranny) I made the laser CNC with RAMPS1.4 which is equipped  with Bluetooth. It has miner issue such as control speed during the printing & pules rate , after that I'm moving to use Due board for faster pulse rate and new features of enhanced Marlin. 
[ @HakanBastedt](https://github.com/HakanBastedt/Marlin4Due/tree/Laser) is the guy who add the TurnkeyTyranny laser feature to due board , he claim , successfully run his laser machine with it both cutting and raster engraving feature, 
also I move on from  Bluetooth to ESP8266 module which is most promising for wireless connection for  All-In-One IOT device , I find[ luc-github](https://github.com/luc-github/ESP8266) code for  wireless bridge and @openhardwarecoza weblaser code for front-end CAM software , the plan is to bind the Peter code inside the Luc code so in final, just connect the machine and start working , no need extra platform or third party to run CAM job, just like new embedded IOT device , all code inside the ESP flash space , doesn't it awesome?? 
also I'm trying to add some feature to Marlin such as auto focus laser head or THC for plasma cutter , the proximity sensor check the material distance in loop function , I hope I could have all these cool guy help for this project an also really appreciated to have your help
BR
